ecommerce/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',include('products.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

ecommerce/products/urls.py
from django.urls import path
from .views import (
    HomeView,
    ItemDetailView,
    CheckOutView,
    add_to_cart,
    remove_from_cart,
    OrderSummary
)


urlpatterns = [
    path('',HomeView.as_view(),name="item-list"),
    path('product/<slug>/',ItemDetailView.as_view(),name='product'),
    path('add-to-cart/<slug>/',add_to_cart,name='add-to-cart'),
    path('remove-from-cart/<slug>/',remove_from_cart,name= 'remove-from-cart'),
    path('order-summary/',OrderSummary.as_view(),name = 'order-summary'),
    #path('checkout/',CheckOutView.as_view(),name='check-out')
    path('check-out/',CheckOutView.as_view(),name='check-out')
]

ecommerce/products/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
# Create your models here.

CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

class Item(models.Model):
    title=models.CharField(max_length=100)
    price=models.FloatField()
    discount_price= models.FloatField(blank= True, null = True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    image = models.ImageField(upload_to='product/',blank= True)
    slug=models.SlugField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("add-to-card", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    item=models.ForeignKey(Item,on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def total_price(self):
        if self.item.discount_price:
            return self.item.discount_price * self.quantity
        else:
            return self.item.price * self.quantity

    def amount_saved(self):
        return (self.item.price - self.item.discount_price) * self.quantity







class Order(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    items=models.ManyToManyField(OrderItem)
    start_date=models.DateTimeField(auto_now_add=True)
    ordered_date=models.DateTimeField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def final_total_price(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.total_price()
        return total

ecommerce/products/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget
PAYMENT_CHOICES =(
    ('S','Stripe'),
    ('P','Paypal')
)


class CheckoutForm(forms.Form):
    street_address = forms.CharField(widget= forms.TextInput(attrs={
        'placeholder': '123 Dinh Bo Linh'
    }))

    apartment_address = forms.CharField(widget= forms.TextInput(attrs={
        'placeholder': 'Apartment or Suite'
    }),required = False)

    country = CountryField(blank_label='Select Country').formfield(widget = CountrySelectWidget(
         attrs={
             'class' : 'custom-select d-block w-100'
         }
    ))
    zip = forms.CharField(widget= forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder' : '123456'
    }))
    same_billing_address = forms.BooleanField(required= False)
    save_info = forms.BooleanField(required= False)
    payment_option = forms.ChoiceField(widget=forms.RadioSelect,choices= PAYMENT_CHOICES)

ecommerce/products/views.py
from django.shortcuts import render,get_object_or_404
from django.shortcuts import redirect
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.contrib import messages
from .forms import CheckoutForm
from requests import request

from .models import Item,Order,OrderItem
from django.views.generic import ListView,DetailView,View
# Create your views here.


class HomeView(ListView):
    model= Item
    paginate_by = 5
    template_name = "products/home-page.html"

class OrderSummary(LoginRequiredMixin,View):
    def get(self,request):
        try:
            order = Order.objects.get(user = request.user , ordered = False)
            return render(request, "products/order-summary.html", {"order": order})
        except ObjectDoesNotExist:
            messages.error(self.request,"You do not have an active order.")
            return redirect("/")




class ItemDetailView(DetailView):
    model= Item
    template_name = "products/product-page.html"

class CheckOutView(View):
    def get(self, *args,**kwargs):
        form = CheckoutForm()
        context = {
            'form' : form
        }
        return render(self.request,"products/checkout-page.html",context)

    def post(self,*args,**kwargs):
        form = CheckoutForm(self.request.POST or None)
        print(self.request.POST)
        if form.is_valid():
            print("The form is valid")
            return redirect('check-out')
        return redirect('check-out')


@login_required
def add_to_cart(request,slug):
    item = get_object_or_404(Item,slug = slug)
    order_item,create = OrderItem.objects.get_or_create(
        user = request.user,
        item = item,
        ordered = False
    )
    order_qs = Order.objects.filter(
        user = request.user,
        ordered = False
    )
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug = slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "This item was updated quantity in your cart.")
            return redirect("product",slug = slug)
        else:
            order.items.add(order_item)
            messages.info(request,"This item was added in your cart.")
            return redirect("product", slug = slug)
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(
            user = request.user,
            ordered_date = ordered_date
        )
        order.items.add(order_item)
        messages.info(request, "This item was added in your cart.")
        return redirect("product",slug = slug)

@login_required
def remove_from_cart(request,slug):
    item = get_object_or_404(Item,slug=slug)
    order_qs = Order.objects.filter(
        user = request.user,
        ordered = False
    )
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug = item.slug).exists():
            order_item = OrderItem.objects.filter(
                user = request.user,
                item = item,
                ordered = False
            )[0]
            order.items.remove(order_item)
            order_item.delete()
            messages.info(request, "This item was removed from your card.")
        else:
            messages.info(request, "This item was not in your card.")
            return redirect("product", slug=slug)
    else:
        messages.info(request, "You do not have an active order.")
        return redirect("product", slug=slug)
    return redirect("product", slug=slug)

ecommerce/products/templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'products/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'products/css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'products/css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

{% include "products/navbar.html" %}

<body>

    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}


    {% include "products/footer.html" %}
    {% include "products/scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

ecommerce/products/templates/products/checkout-page.html
{% extends 'products/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<!--Main layout-->
<main>
    <div class="container wow fadeIn">

        <!-- Heading -->
        <h2 class="my-5 h2 text-center">Checkout form</h2>

        <!--Grid row-->
        <div class="row">

            <!--Grid column-->
            <div class="col-md-8 mb-4">

                <!--Card-->
                <div class="card">

                    <!--                    <form>-->
                    <!--                        {{ form|crispy }}-->
                    <!--                        <button class="btn btn-primary" type='submit'>Checkout</button>-->
                    <!--                    </form>-->
                    <!--Card content-->

                    <form method="POST" class="card-body">
                        {% csrf_token %}
                        <!--address-->
                        <div class="md-form mb-5">
                            <label>Address</label>
                            <!--                            <input type="text" id="address" class="form-control" placeholder="1234 Main St">-->
                            {{ form.street_address }}
                            <!--                            <label for="address" class="">Address</label>-->
                        </div>

                        <!--address-2-->
                        <div class="md-form mb-5">
                            <!--                            <input type="text" id="address-2" class="form-control" placeholder="Apartment or suite">-->
                            {{ form.apartment_address }}
                            <label  class="">Address 2 (optional)</label>
                        </div>

                        <!--Grid row-->
                        <div class="row">

                            <!--Grid column-->
                            <div class="col-lg-4 col-md-12 mb-4">

                                <label for="country">Country</label>
                                <!--                                <select class="custom-select d-block w-100" id="country" required>-->
                                <!--                                    <option value="">Choose...</option>-->
                                <!--                                    <option>United States</option>-->
                                <!--                                </select>-->
                                {{ form.country }}
                                <div class="invalid-feedback">
                                    Please select a valid country.
                                </div>

                            </div>
                            <!--Grid column-->

                            <!--Grid column-->
                            <div class="col-lg-4 col-md-6 mb-4">

                                <label >Zip</label>
                                <!--                                <input type="text" class="form-control" id="zip" placeholder="" required>-->
                                {{ form.zip }}
                                <div class="invalid-feedback">
                                    Zip code required.
                                </div>


                            </div>
                            <!--Grid column-->

                        </div>
                        <!--Grid row-->

                        <hr>

                        <div class="custom-control custom-checkbox">
                            <input {% if form.same_shipping_address.value %} checked {% endif %} type="checkbox" class="custom-control-input" name="same_billing_address" id="same-address">
                            <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
                        </div>
                        <div class="custom-control custom-checkbox">
                            <input  {% if form.save_info.value %} checked {% endif %} type="checkbox" class="custom-control-input"  name="save_info" id="save-info">
                            <label class="custom-control-label" for="save-info" >Save this information for next
                                time</label>
                        </div>

                        <hr>

                        <div class="d-block my-3">
                            {% for value, name in form.fields.payment_option.choices %}
                            <div class="custom-control custom-radio">
                                <input id="{{ name }}" name="payment-option" value="{{ name }}" type="radio" class="custom-control-input"
                                       required>
                                <label class="custom-control-label" for="{{ name }}"> {{ name }} </label>
                            </div>
                            {% endfor %}
                        </div>

                        <hr class="mb-4">
                        <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

                    </form>

                </div>
                <!--/.Card-->

            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-4 mb-4">

                <!-- Heading -->
                <h4 class="d-flex justify-content-between align-items-center mb-3">
                    <span class="text-muted">Your cart</span>
                    <span class="badge badge-secondary badge-pill">3</span>
                </h4>

                <!-- Cart -->
                <ul class="list-group mb-3 z-depth-1">
                    <li class="list-group-item d-flex justify-content-between lh-condensed">
                        <div>
                            <h6 class="my-0">Product name</h6>
                            <small class="text-muted">Brief description</small>
                        </div>
                        <span class="text-muted">$12</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between lh-condensed">
                        <div>
                            <h6 class="my-0">Second product</h6>
                            <small class="text-muted">Brief description</small>
                        </div>
                        <span class="text-muted">$8</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between lh-condensed">
                        <div>
                            <h6 class="my-0">Third item</h6>
                            <small class="text-muted">Brief description</small>
                        </div>
                        <span class="text-muted">$5</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between bg-light">
                        <div class="text-success">
                            <h6 class="my-0">Promo code</h6>
                            <small>EXAMPLECODE</small>
                        </div>
                        <span class="text-success">-$5</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between">
                        <span>Total (USD)</span>
                        <strong>$20</strong>
                    </li>
                </ul>
                <!-- Cart -->

                <!-- Promo code -->
                <form class="card p-2">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Promo code"
                               aria-label="Recipient's username" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-secondary btn-md waves-effect m-0" type="button">Redeem</button>
                        </div>
                    </div>
                </form>
                <!-- Promo code -->

            </div>
            <!--Grid column-->

        </div>
        <!--Grid row-->

    </div>
</main>
{% endblock content %}

ecommerce/products/templates/products/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> CoBocXo.com </a>
    </div>
    <!--/.Copyright-->

  </footer>

ecommerce/products/templates/products/home-page.html
{% extends "products/base.html" %}

{% block content %}
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">
          {% for item in object_list %}
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <img src=" media/{{ item.image }}" class="card-img-top"
                  alt="">

                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong> ${{ item.price }}</strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->
          {% endfor %}

        </div>
        <!--Grid row-->


      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          {% if page_obj.has_previous %}
          <li class="page-item ">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page= {{ page_obj.number }}"> {{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
      <!--Pagination-->

    </div>
  </main>

{% endblock content %}

ecommerce/products/templates/products/item_list.html
{% block content %}
    <h2> Here is the list of items</h2>
    {% for item in items %}
        {{ item }}
    {% endfor %}
{% endblock content %}

ecommerce/products/templates/products/navbar.html
{% load cart_template_tags %}
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/">
        <strong class="blue-text">DJe-commerce</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
<!--          <li class="nav-item active">-->
<!--            <a class="nav-link waves-effect" href="/">Home-->
<!--              <span class="sr-only">(current)</span>-->
<!--            </a>-->
<!--          </li>-->
<!--          <li class="nav-item">-->
<!--            <a class="nav-link waves-effect" href="/checkout">-->
<!--            Checkout</a>-->
<!--          </li>-->
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'order-summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>

          {% endif %}
        </ul>
      </div>

    </div>
</nav>

ecommerce/products/templates/products/order-summary.html
{% extends "products/base.html" %}

{% block content %}
<main>
    <div class="container">
        <div class="table-responsive text-nowrap">
            <h2 style="color:#2196f3!important"><strong> Order Summary</strong></h2>
            <table class="table">
                <thead>
                <tr>
                    <th scope="col"></th>
                    <th scope="col">Item title</th>
                    <th scope="col">Price</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Total Item Price</th>
                </tr>
                </thead>
                <tbody>
                {% for order_item in order.items.all %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ order_item.item.title }}</td>
                    <td>{{ order_item.item.price }}</td>
                    <td>{{ order_item.quantity }}</td>
                    <td>
                        {% if order_item.item.discount_price %}
                        ${{ order_item.total_price }}
                        <span class="badge badge-primary"> Saving ${{ order_item.amount_saved }} </span>
                        {% else %}
                        ${{ order_item.total_price }}
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
                <tr>
                    <td colspan="4"> <b> Total price </b> </td>
                    <td><b> ${{ order.final_total_price }} </b> </td>

                </tr>
                <tr>
                    <td colspan="5">
                        <a href="/check-out/" class="btn btn-warning float-right ml-2">PROCEED TO CHECKOUT</a>
                        <a href="/" class="btn btn-primary float-right mr-2">CONTINUE SHOPPING</a>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</main>

{% endblock content %}

ecommerce/products/templates/products/product-page.html
{% extends 'products/base.html' %}
{% block content %}
<main class="mt-5 pt-4">
  <div class="container dark-grey-text mt-5">

    <!--Grid row-->
    <div class="row wow fadeIn">

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-6 mb-4">

        <!--Content-->
        <div class="p-4">

          <div class="mb-3">
            <a href="">
              <span class="badge purple mr-1">{{ object.get_category_display }}</span>
            </a>

          </div>

          <p class="lead">
              <span class="mr-1">
                <del>${{ object.price }}</del>
              </span>
            <span>${{ object.discount_price }}</span>
          </p>

          <p class="lead font-weight-bold">Description</p>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Et dolor suscipit libero eos atque quia ipsa
            sint voluptatibus!
            Beatae sit assumenda asperiores iure at maxime atque repellendus maiores quia sapiente.</p>


          <a href="{% url 'add-to-cart'  object.slug %}" class="btn btn-primary btn-md my-0 p" >Add to cart
            <i class="fas fa-shopping-cart ml-1"></i>
          </a>
          <a href="{% url 'remove-from-cart'  object.slug %}" class="btn btn-danger btn-md my-0 p" >Remove from cart
            <i class="fas fa-shopping-cart ml-1"></i>
          </a>

        </div>
        <!--Content-->

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

    <hr>

    <!--Grid row-->
    <div class="row d-flex justify-content-center wow fadeIn">

      <!--Grid column-->
      <div class="col-md-6 text-center">

        <h4 class="my-4 h4">Additional information</h4>

        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
          voluptates,
          quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

    <!--Grid row-->
    <div class="row wow fadeIn">

      <!--Grid column-->
      <div class="col-lg-4 col-md-12 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-4 col-md-6 mb-4">

        <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

  </div>
</main>
{% endblock %}